version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbpassword
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqlcustom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
    mysqldata: