version: '3.1'
services:
  postgres:
    image: postgres:9.2.23
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-PGUSER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PGPASS}
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
      TZ: Asia/Ho_Chi_Minh
    volumes:
       - postgres_vl4:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres_vl4: